server.port: 8200

spring.application.name: image-service

app.eureka-server: localhost

logging:
  level:
    root: INFO
    com.example: DEBUG
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    
    

---
spring.profiles: docker

server.port: 8080

app.eureka-server: eureka