version: "2.1"

services:
  image:
    build: app-image-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  gallery:
    build: app-gallery-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka:
    build: app-eureka-server
    mem_limit: 350m
    ports:
      - "8761:8761"

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: app-eureka-auth
    mem_limit: 350m
    depends_on:
      mysql-user:
        condition: service_healthy

  customer-service:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: customer-service
    mem_limit: 350m
    depends_on:
      mysql-customer:
        condition: service_healthy

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: app-eureka-zuul
    mem_limit: 350m
    ports:
      - "8080:8080"

  mysql-user:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=user_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: '/usr/bin/mysql --user=user --password=password --execute "SHOW DATABASES;"'
      interval: 20s
      timeout: 5s
      retries: 10

  mysql-customer:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=customer_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      test: '/usr/bin/mysql --user=user --password=password --execute "SHOW DATABASES;"'
      interval: 20s
      timeout: 5s
      retries: 10
#    networks:
#      - network-eureka

#networks:
#  network-eureka:
