server.port: 9100
spring.application.name: auth-service
logging:
  level:
    root: INFO
    com.example: DEBUG


app.eureka-server: localhost

#spring.datasource:
#  url: jdbc:mysql://localhost/user-db
#  username: user
#  password: pwd
  
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
      
                
---
spring.profiles: docker

app.eureka-server: eureka
