server.port: 9500
spring.application.name: customer-service
logging:
  level:
    root: INFO
    com.example: DEBUG

app.eureka-server: localhost

spring.datasource:
  url: jdbc:mysql://localhost/customer_db
  username: user
  password: password
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring.profiles: docker

app.eureka-server: eureka
spring.datasource.url: jdbc:mysql://mysql-customer/customer_db
